# Generated by Django 5.0.6 on 2024-08-03 12:10

import ravi.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ravi', '0002_hlbasicdetailform_plbasicdetailform_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerprofile',
            name='coapplicant_age',
            field=models.IntegerField(default='', max_length=3, validators=[ravi.models.validate_age]),
        ),
    ]
