# Generated by Django 5.0.6 on 2024-08-08 03:10

import ravi.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ravi', '0004_alter_customerprofile_coapplicant_age'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerprofile',
            name='coapplicant_email_id',
            field=models.EmailField(max_length=254, validators=[ravi.models.validate_email]),
        ),
        migrations.AlterField(
            model_name='customerprofile',
            name='email_id',
            field=models.EmailField(max_length=254, validators=[ravi.models.validate_email]),
        ),
        migrations.AlterField(
            model_name='hlbasicdetailform',
            name='email',
            field=models.EmailField(max_length=254, validators=[ravi.models.validate_email]),
        ),
        migrations.AlterField(
            model_name='personaldetail',
            name='email',
            field=models.EmailField(max_length=254, validators=[ravi.models.validate_email]),
        ),
        migrations.AlterField(
            model_name='personaldetail',
            name='work_email',
            field=models.EmailField(max_length=254, validators=[ravi.models.validate_email]),
        ),
    ]
