# Generated by Django 5.0.6 on 2024-08-02 17:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('anusha', '0002_goldbasicdetailform_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='basicdetailform',
            name='loantype',
        ),
    ]
