# Generated by Django 5.0.6 on 2024-08-06 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anusha', '0003_remove_basicdetailform_loantype'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeneralInsurance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('insurance_name', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('mobile_number', models.CharField(max_length=15, unique=True)),
                ('email_id', models.EmailField(max_length=254)),
                ('messgae', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='healthInsurance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('insurance_name', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('mobile_number', models.CharField(max_length=15, unique=True)),
                ('email_id', models.EmailField(max_length=254)),
                ('messgae', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='LifeInsurance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('insurance_name', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('mobile_number', models.CharField(max_length=15, unique=True)),
                ('email_id', models.EmailField(max_length=254)),
                ('messgae', models.TextField()),
            ],
        ),
        migrations.RenameModel(
            old_name='Insurance',
            new_name='AllInsurance',
        ),
    ]
