# Generated by Django 5.0.6 on 2024-08-06 09:23

import anusha.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anusha', '0004_generalinsurance_healthinsurance_lifeinsurance_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goldloanapplication',
            name='state',
            field=models.CharField(max_length=50, validators=[anusha.models.validate_only_letters]),
        ),
    ]
