# Generated by Django 5.0.6 on 2024-08-08 10:43

import anusha.models
import django.core.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anusha', '0005_alter_goldloanapplication_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basicdetailform',
            name='required_loan_amount',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[anusha.models.validate_amount]),
        ),
        migrations.AlterField(
            model_name='basicdetailform',
            name='terms_accepted',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='goldbasicdetailform',
            name='terms_accepted',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='loanapplication',
            name='co_applicant_email_id',
            field=models.EmailField(default='a', max_length=254, validators=[django.core.validators.EmailValidator()]),
        ),
        migrations.AlterField(
            model_name='loanapplication',
            name='co_applicant_first_name',
            field=models.CharField(default=django.utils.timezone.now, max_length=50, validators=[anusha.models.validate_only_letters]),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='loanapplication',
            name='co_applicant_occupation',
            field=models.CharField(default='a', max_length=50, validators=[anusha.models.validate_only_letters]),
        ),
        migrations.AlterField(
            model_name='loanapplication',
            name='ref1_mobile',
            field=models.CharField(blank=True, max_length=10, null=True, validators=[anusha.models.validate_mobile_number]),
        ),
        migrations.AlterField(
            model_name='loanapplication',
            name='ref2_mobile',
            field=models.CharField(blank=True, max_length=10, null=True, validators=[anusha.models.validate_mobile_number]),
        ),
    ]
